name: Deploy Zola blog to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Install Zola
      #   run: |
      #     wget https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
      #     tar xzf zola-*.tar.gz
      #     sudo mv zola /usr/local/bin/

      - name: Build
        # run: zola build
        # GITHUB_TOKEN has Read and Write permissions.
        # Workflows have read and write permissions in the repository for all scopes.
        uses: shalzz/zola-deploy-action@v0.17.1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Deploy to maruska-blog.github.io
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     personal_token: ${{ secrets.DEPLOY_TOKEN }}
      #     external_repository: maruska-blog/maruska-blog.github.io
      #     publish_branch: main
      #     publish_dir: ./public
